name: Deploy to Github Pages # Action 的名称，随便写
on:
  push:
    branches:
      - dev # 这里是限定了 Action 的触发条件，我限定只有在 dev 分支发生 push 动作时才触发
jobs:
  deploy:
    runs-on: ubuntu-latest # 虚拟机系统，Ubuntu 标配
    strategy:
      matrix:
        node-version: [12.x] # 这里设置好 node 的版本
    steps:
      - uses: actions/checkout@v1 # 检查
      - name: Use Node.js ${{ matrix.node-version }} # 启动 node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules # 缓存 node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install Packages # 安装依赖，懂的都懂
        run: npm install
      - name: Build page # 构建静态文件，这个要看你的 package.json 中 script 的内容，你需要熟知自己项目生成静态文件的路径
        run: npm run build
      - name: Deploy to Github Pages # 部署到 Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.HEXO_DEPLOY_KEY }} # 这里就是刚刚 Secrets 中设置的私钥的名称，所以我说不要太为难自己嘛
          publish_dir: ./public # 项目构建静态文件的目录